set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_PREFIX  arm-linux-gnueabihf)
set(CMAKE_C_COMPILER   ${CMAKE_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${CMAKE_PREFIX}-g++)
set(CMAKE_STRIP        ${CMAKE_PREFIX}-strip)

set(CMAKE_SYSROOT /opt/sysroot/debian-armhf)

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR}
    "${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig"
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
